import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: [
      'components/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',
    ],
  },
  esbuild: {
    jsx: 'automatic',
  },
  resolve: {
    alias: {
      // Handle workspace dependencies with absolute paths
      '@hautechai/webui.appbar': resolve(__dirname, './components/AppBar/src'),
      '@hautechai/webui.appbarmobile': resolve(__dirname, './components/AppBarMobile/src'),
      '@hautechai/webui.aspectratio': resolve(__dirname, './components/AspectRatio/src'),
      '@hautechai/webui.avatar': resolve(__dirname, './components/Avatar/src'),
      '@hautechai/webui.badge': resolve(__dirname, './components/Badge/src'),
      '@hautechai/webui.bottomsheet': resolve(__dirname, './components/BottomSheet/src'),
      '@hautechai/webui.box': resolve(__dirname, './components/Box/src'),
      '@hautechai/webui.button': resolve(__dirname, './components/Button/src'),
      '@hautechai/webui.buttonbase': resolve(__dirname, './components/ButtonBase/src'),
      '@hautechai/webui.card': resolve(__dirname, './components/Card/src'),
      '@hautechai/webui.checkbox': resolve(__dirname, './components/Checkbox/src'),
      '@hautechai/webui.chip': resolve(__dirname, './components/Chip/src'),
      '@hautechai/webui.column': resolve(__dirname, './components/Column/src'),
      '@hautechai/webui.contextmenu': resolve(__dirname, './components/ContextMenu/src'),
      '@hautechai/webui.counter': resolve(__dirname, './components/Counter/src'),
      '@hautechai/webui.dataitem': resolve(__dirname, './components/DataItem/src'),
      '@hautechai/webui.divider': resolve(__dirname, './components/Divider/src'),
      '@hautechai/webui.dropdown': resolve(__dirname, './components/Dropdown/src'),
      '@hautechai/webui.field': resolve(__dirname, './components/Field/src'),
      '@hautechai/webui.fileinput': resolve(__dirname, './components/FileInput/src'),
      '@hautechai/webui.floatingpanel': resolve(__dirname, './components/FloatingPanel/src'),
      '@hautechai/webui.fullscreen': resolve(__dirname, './components/FullScreen/src'),
      '@hautechai/webui.hint': resolve(__dirname, './components/Hint/src'),
      '@hautechai/webui.hovercontrols': resolve(__dirname, './components/HoverControls/src'),
      '@hautechai/webui.icon': resolve(__dirname, './components/Icon/src'),
      '@hautechai/webui.iconbutton': resolve(__dirname, './components/IconButton/src'),
      '@hautechai/webui.imageinput': resolve(__dirname, './components/ImageInput/src'),
      '@hautechai/webui.imageinputwithsamples': resolve(__dirname, './components/ImageInputWithSamples/src'),
      '@hautechai/webui.linkbutton': resolve(__dirname, './components/LinkButton/src'),
      '@hautechai/webui.logo': resolve(__dirname, './components/Logo/src'),
      '@hautechai/webui.masonry': resolve(__dirname, './components/Masonry/src'),
      '@hautechai/webui.menu': resolve(__dirname, './components/Menu/src'),
      '@hautechai/webui.menuitem': resolve(__dirname, './components/MenuItem/src'),
      '@hautechai/webui.modal': resolve(__dirname, './components/Modal/src'),
      '@hautechai/webui.operationitem': resolve(__dirname, './components/OperationItem/src'),
      '@hautechai/webui.pagination': resolve(__dirname, './components/Pagination/src'),
      '@hautechai/webui.panel': resolve(__dirname, './components/Panel/src'),
      '@hautechai/webui.popover': resolve(__dirname, './components/Popover/src'),
      '@hautechai/webui.previews': resolve(__dirname, './components/Previews/src'),
      '@hautechai/webui.price': resolve(__dirname, './components/Price/src'),
      '@hautechai/webui.progress': resolve(__dirname, './components/Progress/src'),
      '@hautechai/webui.row': resolve(__dirname, './components/Row/src'),
      '@hautechai/webui.segmentedcontrol': resolve(__dirname, './components/SegmentedControl/src'),
      '@hautechai/webui.sidebar': resolve(__dirname, './components/Sidebar/src'),
      '@hautechai/webui.slider': resolve(__dirname, './components/Slider/src'),
      '@hautechai/webui.switch': resolve(__dirname, './components/Switch/src'),
      '@hautechai/webui.table': resolve(__dirname, './components/Table/src'),
      '@hautechai/webui.textarea': resolve(__dirname, './components/TextArea/src'),
      '@hautechai/webui.textbutton': resolve(__dirname, './components/TextButton/src'),
      '@hautechai/webui.textinput': resolve(__dirname, './components/TextInput/src'),
      '@hautechai/webui.theme': resolve(__dirname, './components/Theme/src'),
      '@hautechai/webui.themeprovider': resolve(__dirname, './components/ThemeProvider/src'),
      '@hautechai/webui.tile': resolve(__dirname, './components/Tile/src'),
      '@hautechai/webui.tiletabgroup': resolve(__dirname, './components/TileTabGroup/src'),
      '@hautechai/webui.tiletabitem': resolve(__dirname, './components/TileTabItem/src'),
      '@hautechai/webui.tooltip': resolve(__dirname, './components/Tooltip/src'),
      '@hautechai/webui.typography': resolve(__dirname, './components/Typography/src'),
      '@hautechai/webui.user': resolve(__dirname, './components/User/src'),
      '@hautechai/webui.userbalance': resolve(__dirname, './components/UserBalance/src'),
    },
  },
});